Update README.md
google-github-actions/deploy-appengine pull request #9
Opened 2020-11-17 20:26 UTC by oiegorov-geeksforless

Added more description to "promote" argument of deploy-appengine action

2020-12-15 01:17 UTC, averikitsch commented on README.md
> +  receive all traffic. If not specified behavior defaults to promote.
```suggestion
- `promote`: (Optional) Promote the deployed version to receive all traffic. 
  Possible values: ''|'true'|true|'false'|false, if not specified behavior defaults to promote.
```

2020-12-15 01:17 UTC, averikitsch requested changes
Sorry about missing this! Can you update to remove the double wording?

2020-12-16 11:50 UTC, oiegorov-geeksforless commented
Thanks! Updated to remove double wording.

2020-12-16 15:51 UTC, averikitsch approved these changes

2020-12-16 15:51 UTC, merged